spring:
  application:
    name: BatchProcessingCSVFiles

  profiles:
    active: postgres

  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false
      name: importProductJob
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
      max-var-char-length: 1000
      isolation-level-for-create: ISOLATION_READ_COMMITTED

  sql:
    init:
      mode: always